# Makefile for the Paravel 9rd4 repo.

#SHELL := /bin/bash

#REPO_KEY = "Paravel Ubuntu 20.04 Test Key"


sign:	clean sane
	gpgconf --kill gpg-agent
	rpm --resign Packages/*.rpm
	createrepo .


post:	sane
	rsync -rptgoDv --copy-links --delete --exclude Makefile --exclude sanity_check.sh . software.paravelsystems.com::redhat_9/9rd4/

sane:	
	./sanity_check.sh  

clean:
	rm -rf repodata
	rm -f Packages/*.sig
